/**
 * mockReportData.js
 * Authoritative offline fallback data modeled on Pump-A12 Inboard Ceramic Seal Failure.
 * Conforms 100% to backend/api/rca_schemas.py EightDIncidentReport specification.
 */

export const mockReportData = {
  report_id: "8D-2023-PUMP-A12-001",
  created_at: "2023-11-04T08:30:00Z",
  asset_tag: "Pump-A12",
  severity_score: 8,
  occurrence_score: 6,
  detection_score: 7,
  rpn_score: 336,
  checksum_sha256: "4f8a9b2c7e1d3f6a8e5b0c9d2a4f7e1b3c5a8d0e2f4a6b8c0d2e4f6a8b0c2d4e",
  
  d1_team: {
    leader: "Dr. Sarah Jenkins - Lead Mechanical Reliability Specialist",
    champion: "David Ross - VP Plant Operations & Reliability",
    members: [
      "Carlos Mendez - Operations Supervisor",
      "Dr. Elena Rostova - Vibration Analyst",
      "Tom Bradley - OEM Field Specialist",
      "Rachel Kim - Quality Assurance Engineer"
    ],
    facilitator: "Dr. Aris Thorne - Certified RCA Specialist"
  },

  d2_problem: {
    incident_title: "Catastrophic Inboard Ceramic Mechanical Seal Fracture & High-Velocity Leakage",
    what: "Catastrophic inboard ceramic mechanical seal fracture with high-velocity barrier fluid leakage and secondary impeller vibration excursion",
    where: "Coolant Loop B, Skid 04, Primary Circulation Pump Pump-A12",
    when: "2023-11-04 08:14:22 UTC during steady-state high-throughput operations",
    who: "Control Room Operator J. Vance & Automated Vibration Supervisory System DCS-04",
    why: "Loss of primary cooling barrier, risk of pump impeller seizure, and containment protocol breach",
    how: "Accelerometer telemetry spike to 5.8 mm/s triggering level-2 supervisory alarm and automated trip sequence",
    how_many: "1 pump offline (1,200 gpm flow deficit); 2 sister pumps on elevated alert; 0 personnel injuries",
    operational_impact: "14.5 Hours Total Unplanned Plant Downtime · Primary Loop Cooling Deficit · $84,200 Total Estimated Financial Impact",
    is_not_analysis: {
      "Is Defect": "Ceramic face thermal fracture and brittle fragmentation on Pump-A12",
      "Is Not Defect": "Outboard secondary dynamic elastomeric O-ring seal failure",
      "Is Location": "Inboard seal cavity of Primary Loop B circulation pump",
      "Is Not Location": "Auxiliary booster pump or secondary cooling bypass circuit",
      "Is Timing": "Occurred during thermal ramp transition under high operating throughput",
      "Is Not Timing": "Did not occur during cold shutdown, low-flow idle, or standby state"
    }
  },

  d3_containment: [
    {
      action_id: "ICA-01",
      action: "Isolate Pump-A12 by actuating motor-operated isolation valves MOV-101 and MOV-102; lock out electrical feed breaker CB-412.",
      verified_effective: true,
      effectiveness_pct: 100.0,
      owner: "Carlos Mendez - Shift Operations Lead",
      implementation_date: "2023-11-04T08:22:00Z",
      verification_method: "Zero differential pressure confirmed across bypass manifold; zero barrier fluid leakage detected.",
      status: "IMPLEMENTED",
      citation_ids: ["CITE-PUMP-001", "CITE-PUMP-002"]
    },
    {
      action_id: "ICA-02",
      action: "Engage standby auxiliary cooling loop Pump-A11 to maintain 1,200 gpm nominal plant flow.",
      verified_effective: true,
      effectiveness_pct: 95.0,
      owner: "J. Vance - DCS Operator",
      implementation_date: "2023-11-04T08:35:00Z",
      verification_method: "Thermal sensors confirm Primary Loop B steady-state operating temperature restored within nominal boundaries.",
      status: "IMPLEMENTED",
      citation_ids: ["CITE-PUMP-002"]
    }
  ],

  d4_root_causes: {
    occurrence_root_cause: "Thermal shock induced by unconditioned high-flow coolant ramp causing brittle stress fracture of the ceramic seal face.",
    escape_root_cause: "Supervisory telemetry threshold was set at 6.0 mm/s rather than OEM recommended 4.5 mm/s early warning threshold.",
    citation_grounding_ratio: 0.85,
    five_why_chain: [
      {
        why_id: "WHY-1",
        level: 1,
        cause_statement: "Pump-A12 experienced emergency trip due to high vibration alarm exceeding trip setpoint.",
        parent_node_id: null,
        citation_ids: ["CITE-PUMP-001"],
        is_root_cause: false,
        is_unsubstantiated: false,
        assumed_flag: false,
        verification_notes: "Confirmed by DCS supervisory alarm logs at 08:14:22 UTC."
      },
      {
        why_id: "WHY-2",
        level: 2,
        cause_statement: "Vibration excursion was generated by dynamic mechanical unbalance and barrier fluid loss in the seal gland.",
        parent_node_id: "WHY-1",
        citation_ids: ["CITE-PUMP-001", "CITE-PUMP-003"],
        is_root_cause: false,
        is_unsubstantiated: false,
        assumed_flag: false,
        verification_notes: "Physical teardown revealed complete loss of barrier fluid pressure."
      },
      {
        why_id: "WHY-3",
        level: 3,
        cause_statement: "The mechanical seal cavity lost pressure integrity because the inboard ceramic stationary face suffered catastrophic brittle fracture.",
        parent_node_id: "WHY-2",
        citation_ids: ["CITE-PUMP-003"],
        is_root_cause: false,
        is_unsubstantiated: false,
        assumed_flag: false,
        verification_notes: "Metallurgical laboratory SEM inspection confirmed brittle cleavage fracture."
      },
      {
        why_id: "WHY-4",
        level: 4,
        cause_statement: "The ceramic face fractured under extreme localized thermal stress caused by sudden temperature delta during flow step increase.",
        parent_node_id: "WHY-3",
        citation_ids: ["CITE-PUMP-004"],
        is_root_cause: false,
        is_unsubstantiated: false,
        assumed_flag: false,
        verification_notes: "Temperature telemetry recorded 42°C delta in under 90 seconds."
      },
      {
        why_id: "WHY-5",
        level: 5,
        cause_statement: "Standard Operating Procedure SOP-PUMP-042 lacked mandatory thermal pre-conditioning dwell stages prior to high-flow ramp-up.",
        parent_node_id: "WHY-4",
        citation_ids: ["CITE-PUMP-005"],
        is_root_cause: true,
        is_unsubstantiated: false,
        assumed_flag: false,
        verification_notes: "Document review confirmed SOP Revision 3 permitted unconstrained flow ramping without thermal soak."
      }
    ],
    fishbone_analysis: {
      branches: [
        {
          category: "Man",
          causes: [
            "Operator executed flow ramp without manual thermal soak verification",
            "Shift handover lacked explicit thermal status briefing"
          ],
          citation_ids: ["CITE-PUMP-002"],
          is_unsubstantiated: false,
          assumed_flag: false
        },
        {
          category: "Machine",
          causes: [
            "Ceramic stationary seal face had low fracture toughness under rapid delta-T",
            "Shaft alignment was within tolerance but lacked dynamic thermal expansion allowance"
          ],
          citation_ids: ["CITE-PUMP-003"],
          is_unsubstantiated: false,
          assumed_flag: false
        },
        {
          category: "Material",
          causes: [
            "Standard alumina ceramic seal face utilized instead of silicon carbide (SiC)",
            "Barrier fluid viscosity exceeded optimal thermal transfer rating at cold start"
          ],
          citation_ids: ["CITE-PUMP-004"],
          is_unsubstantiated: false,
          assumed_flag: false
        },
        {
          category: "Method",
          causes: [
            "SOP-PUMP-042 lacked mandatory thermal dwell stages before high-velocity flow ramp",
            "Preventative maintenance schedule did not include seal face acoustic emission scan"
          ],
          citation_ids: ["CITE-PUMP-005"],
          is_unsubstantiated: false,
          assumed_flag: false
        },
        {
          category: "Measurement",
          causes: [
            "Vibration trip setpoint set at 6.0 mm/s rather than OEM recommended 4.5 mm/s",
            "Seal cavity RTD sensor had 15-second telemetry sampling lag"
          ],
          citation_ids: ["CITE-PUMP-001"],
          is_unsubstantiated: false,
          assumed_flag: false
        },
        {
          category: "Environment",
          causes: [
            "Ambient skid temperature at 12°C increased thermal gradient against hot process fluid",
            "Vibration harmonics from adjacent booster skid Skid-03"
          ],
          citation_ids: [],
          is_unsubstantiated: true,
          assumed_flag: true
        }
      ]
    }
  },

  d5_permanent_actions: [
    {
      pca_id: "PCA-01",
      action: "Upgrade mechanical seal material specification to sintered Reaction-Bonded Silicon Carbide (SiC) with Diamond-Like Carbon (DLC) coating for high thermal shock resistance.",
      target_cause_id: "WHY-3 / WHY-4",
      owner: "Tom Bradley - OEM Field Specialist",
      target_date: "2023-11-20T00:00:00Z",
      feasibility_score: 9,
      risk_assessment: "Low implementation risk; drop-in replacement cartridge approved by pump manufacturer.",
      validation_plan: "Conduct 100-hour continuous thermal cycling qualification test under 60°C step changes.",
      status: "IN_PROGRESS"
    },
    {
      pca_id: "PCA-02",
      action: "Revise SOP-PUMP-042 to mandate 15-minute thermal soak dwell stage with DCS automated ramp interlock preventing rapid flow steps.",
      target_cause_id: "WHY-5",
      owner: "Dr. Sarah Jenkins - Lead Reliability Specialist",
      target_date: "2023-11-15T00:00:00Z",
      feasibility_score: 10,
      risk_assessment: "Negligible operational penalty; adds 15 minutes to cold start procedure.",
      validation_plan: "Audit 5 consecutive operational ramp cycles using DCS automated compliance logs.",
      status: "IMPLEMENTED"
    },
    {
      pca_id: "PCA-03",
      action: "Recalibrate vibration supervisory alarm limits: set pre-alarm at 3.8 mm/s and emergency trip threshold at 4.5 mm/s.",
      target_cause_id: "Measurement (Escape Cause)",
      owner: "Dr. Elena Rostova - Vibration Analyst",
      target_date: "2023-11-10T00:00:00Z",
      feasibility_score: 10,
      risk_assessment: "Zero hardware cost; configuration change within DCS supervisory parameters.",
      validation_plan: "Simulate test signal injection into DCS vibration channel; verify trip interlock response < 50ms.",
      status: "IMPLEMENTED"
    }
  ],

  d6_validation: {
    validation_id: "VAL-8D-2023-01",
    metrics: "Zero seal face cracking, vibration RMS velocity < 2.2 mm/s across 500 operating hours, 100% adherence to thermal dwell protocol.",
    validation_date: "2023-12-15T00:00:00Z",
    status: "IN_PROGRESS",
    verified_by: "Rachel Kim - Quality Assurance Engineer"
  },

  d7_preventative_controls: {
    sop_updates: [
      "SOP-PUMP-042 Revision 4: Mandatory 15-minute thermal pre-conditioning dwell stage prior to high-flow ramp-up",
      "SOP-PUMP-018 Revision 2: Pre-startup laser shaft alignment and barrier fluid pressure decay test protocol"
    ],
    pm_updates: [
      "PM-410 Revision 3: High-frequency ultrasonic seal acoustic emission scanning every 500 operating hours",
      "PM-412 Revision 2: Quarterly RTD sensor calibration and barrier fluid thermal degradation analysis"
    ],
    oem_deviations: [
      {
        parameter_name: "Peak Vibration Velocity (RMS)",
        oem_envelope_limit: 5.0,
        actual_incident_value: 5.8,
        deviation_percent: 16.0,
        unit: "mm/s",
        is_exceeded: true,
        severity_level: "CRITICAL",
        recommended_action: "Lower trip threshold from 6.0 mm/s to 4.5 mm/s; replace alumina seal with silicon carbide"
      },
      {
        parameter_name: "Thermal Gradient Ramp Rate",
        oem_envelope_limit: 15.0,
        actual_incident_value: 28.0,
        deviation_percent: 86.7,
        unit: "°C/min",
        is_exceeded: true,
        severity_level: "CRITICAL",
        recommended_action: "Implement automated DCS ramp rate limiter restricting rate-of-rise to ≤ 10°C/min"
      },
      {
        parameter_name: "Barrier Fluid Seal Chamber Pressure",
        oem_envelope_limit: 3.5,
        actual_incident_value: 1.2,
        deviation_percent: -65.7,
        unit: "bar",
        is_exceeded: true,
        severity_level: "HIGH",
        recommended_action: "Install low-pressure interlock switch to trip motor if seal gland pressure drops below 2.8 bar"
      }
    ],
    historical_matches: [
      {
        matched_report_id: "NM-2023-08-PUMP",
        title: "Near-Miss: Elevated Vibration and Thermal Transient on Sister Feedwater Pump",
        similarity_score: 0.92,
        matching_symptoms: [
          "Rapid vibration rise to 5.2 mm/s",
          "Ceramic seal face micro-cracking",
          "Abrupt flow transition without soak stage"
        ],
        preventative_recommendations: [
          "Standardize thermal ramp dwell times across all primary coolant skid pumps",
          "Accelerate transition from alumina ceramic to sintered silicon carbide seal cartridges"
        ],
        equipment_family: "Centrifugal High-Pressure Circulation Pumps (Sulzer / Flowserve)",
        recurring_risk_assessment: "High probability of recurrence on sister assets Pump-A11 and Pump-A13 if SOP is not uniformly enforced."
      },
      {
        matched_report_id: "RCA-2022-PUMP-B04",
        title: "Seal Barrier Fluid Contamination and Face Degradation Incident",
        similarity_score: 0.76,
        matching_symptoms: [
          "Seal chamber barrier pressure drop",
          "Dynamic O-ring thermal hardening"
        ],
        preventative_recommendations: [
          "Implement continuous barrier fluid pressure monitoring with DCS interlocks"
        ],
        equipment_family: "Cooling Skid Auxiliary Pumps",
        recurring_risk_assessment: "Moderate similarity; primary failure mechanism was chemical degradation rather than thermal shock."
      }
    ],
    horizontal_assets: [
      "Pump-A11 (Primary Loop B standby pump)",
      "Pump-A13 (Primary Loop A main circulation pump)",
      "Pump-B01 (Secondary Loop A high-pressure circulation pump)"
    ],
    status: "IMPLEMENTED"
  },

  d8_recognition: {
    recognition_notes: "The multi-disciplinary investigation team demonstrated outstanding agility and technical rigor. Containment isolation was achieved in under 8 minutes, averting secondary impeller damage, environmental fluid breach, or personal injury.",
    approver_name: "Dr. Marcus Vance",
    approver_role: "Director of Quality Assurance & Plant Reliability",
    signoff_status: "APPROVED",
    signoff_date: "2023-11-06T16:30:00Z",
    signature_hash: "SIG-SHA256: 8f4a2b91c0e3579d1a84f67c2d9e0b1a4f3c7e8d2a5b6c9e0f1a3b4c5d6e7f8",
    lessons_learned: "1. Rapid operational ramping without controlled thermal conditioning represents a critical failure mode for ceramic components. 2. Engineering controls (DCS automated rate limiters) must supersede procedural adherence alone. 3. Sister assets sharing identical mechanical envelopes must immediately inherit preventative updates.",
    financial_impact_total_usd: 84200.0,
    downtime_hours_total: 14.5
  },

  timeline: [
    {
      event_id: "EVT-001",
      timestamp: "2023-11-04T07:45:00Z",
      event_type: "MAINTENANCE_LOG",
      description: "Pre-shift inspection completed by technician; Pump-A12 bearing temperatures and seal barrier fluid levels verified within normal ranges.",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-002"],
      parameters: {
        bearing_temp_c: 44.2,
        barrier_press_bar: 3.4
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-002",
      timestamp: "2023-11-04T08:10:00Z",
      event_type: "OPERATOR_ACTION",
      description: "Operator initiated throughput increase command on Coolant Loop B; flow ramp target set from 600 gpm to 1,200 gpm.",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-002"],
      parameters: {
        flow_target_gpm: 1200,
        ramp_rate_gpm_min: 200
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-003",
      timestamp: "2023-11-04T08:13:30Z",
      event_type: "THRESHOLD_EXCEEDED",
      description: "Rapid thermal transient recorded in seal gland; temperature climbed from 38°C to 80°C (28°C/min ramp rate vs 15°C/min OEM envelope).",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-004"],
      parameters: {
        thermal_gradient_c_min: 28.0,
        deviation_pct: 86.7,
        is_exceeded: true
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-004",
      timestamp: "2023-11-04T08:14:05Z",
      event_type: "TELEMETRY_ALARM",
      description: "Accelerometer channel VIB-A12-X detected vibration surge to 4.8 mm/s; DCS level-1 advisory alarm generated.",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-001"],
      parameters: {
        vibration_mm_s: 4.8,
        deviation_pct: -4.0,
        is_exceeded: false
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-005",
      timestamp: "2023-11-04T08:14:22Z",
      event_type: "SYSTEM_FAILURE",
      description: "Catastrophic inboard ceramic seal face fracture; vibration spiked sharply to 5.8 mm/s (+16% over OEM 5.0 mm/s envelope) triggering automated emergency trip.",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-001", "CITE-PUMP-003"],
      parameters: {
        vibration_mm_s: 5.8,
        deviation_pct: 16.0,
        is_exceeded: true
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-006",
      timestamp: "2023-11-04T08:22:00Z",
      event_type: "OPERATOR_ACTION",
      description: "Shift team executed emergency isolation protocol: closed isolation valves MOV-101/102 and engaged lockout CB-412.",
      equipment_tag: "Pump-A12",
      citation_ids: ["CITE-PUMP-001"],
      parameters: {
        isolation_time_sec: 458
      },
      is_unsubstantiated: false
    },
    {
      event_id: "EVT-007",
      timestamp: "2023-11-04T08:35:00Z",
      event_type: "OPERATOR_ACTION",
      description: "Standby circulation pump Pump-A11 brought online; nominal cooling loop flow re-established at 1,200 gpm.",
      equipment_tag: "Pump-A11",
      citation_ids: ["CITE-PUMP-002"],
      parameters: {
        restored_flow_gpm: 1200
      },
      is_unsubstantiated: false
    }
  ],

  citations: [
    {
      citation_id: "CITE-PUMP-001",
      source_doc: "DCS_Telemetry_Log_20231104.csv",
      excerpt: "Channel VIB-A12-X logged instantaneous spike from 2.1 mm/s to 5.8 mm/s at 08:14:22 UTC. Supervisory trip relay energized at 08:14:23 UTC.",
      section: "Telemetry Logs / Loop B",
      page_or_line: "Line 1422",
      title: "DCS Channel VIB-A12-X Telemetry Record",
      confidence: 0.99
    },
    {
      citation_id: "CITE-PUMP-002",
      source_doc: "Control_Room_Shift_Log_20231104.txt",
      excerpt: "08:14:30 UTC Operator Vance acknowledged emergency vibration trip on Pump-A12. At 08:22:00 isolation completed. At 08:35:00 standby Pump-A11 successfully brought online.",
      section: "Shift Logbook B",
      page_or_line: "Page 4, Log 88",
      title: "Shift Operations Logbook - 04 Nov 2023",
      confidence: 0.98
    },
    {
      citation_id: "CITE-PUMP-003",
      source_doc: "Metallurgical_Failure_Analysis_Report_MFA-2023-412.pdf",
      excerpt: "Stationary seal ring displayed extensive macro-cleavage and radial thermal cracking originating from the inner diameter. Fracture morphology is consistent with extreme thermal stress shock.",
      section: "Section 4.2 Fracture Morphology",
      page_or_line: "Page 12",
      title: "Metallurgical Lab Analysis Report MFA-2023-412",
      confidence: 0.96
    },
    {
      citation_id: "CITE-PUMP-004",
      source_doc: "Pump_OEM_Manual_Sulzer_ZE.pdf",
      excerpt: "Section 6.4: Under no circumstances should the thermal ramp rate exceed 15°C/min for standard ceramic mechanical seals. Exceeding this boundary induces thermal shock fracture.",
      section: "Section 6.4 Operating Limits",
      page_or_line: "Page 88",
      title: "Sulzer ZE Heavy-Duty Process Pump Manual",
      confidence: 0.95
    },
    {
      citation_id: "CITE-PUMP-005",
      source_doc: "SOP-PUMP-042_Rev3.pdf",
      excerpt: "Step 4.1 instructed operators to increase flow directly to target setpoint once motor speed achieved nominal 1,750 RPM, omitting thermal pre-conditioning hold stages.",
      section: "Operating Procedure 4.1",
      page_or_line: "Page 6",
      title: "Standard Operating Procedure SOP-PUMP-042 Rev 3",
      confidence: 0.94
    }
  ]
};
